
name: todo-ls-backend
on:
  push:
    branches:
      - tester
jobs:
  test-build-and-deploy:
    runs-on: ubuntu-latest
    env: ${{ secrets.ENV }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Run lint
        run: npm run lint

      # - name: Copy env values
      #   run: cp ../.env ./.env

      - name: Run unit tests
        run: npm test

      - name: Build
        run: npm run build

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: "dist, node_modules"
          target: "todo-ls-backend"