
name: todo-ls-backend
on:
  push:
    branches:
      - develop
jobs:
  test-build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Copy env values
        run: cp ../.env ./.env

      - name: Run unit tests
        # Special treatment for my crappy server (normally 'npm test')
        run: npx jest --clearCache && npx jest --runInBand --no-cache 

      - name: Build
        run: npm run build

      - name: Copy env values for build
        run: cp ../.env ./dist/.env

      - name: Restart process
        run: pm2 restart todo-ls-backend --update-env # the pm2 process must be defined