
name: todo-ls-backend
on:
  push:
    branches:
      - tester
jobs:
  test-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      # - name: Run lint
      #   run: npm run lint

      # - name: Copy env values
      #   run: cp ../.env ./.env

      # - name: Run unit tests
      #   # Special treatment for my crappy server (normally 'npm test')
      #   run: npx jest --clearCache && npx jest --runInBand --no-cache 

      - name: Build
        run: npm run build

      - name: tester
        run: ls -la src/

      # - name: Copy env values for build
      #   run: cp ../.env ./dist/.env

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          # host: ${{ secrets.HOST }}
          host: ec2-18-191-96-173.us-east-2.compute.amazonaws.com
          # username: ${{ secrets.USERNAME }}
          username: ec2-user
          port: 22
          # port: ${{ secrets.PORT }}
          key: -----BEGIN RSA PRIVATE KEY-----MIIEpQIBAAKCAQEAv9hSmqGL+cPG3H8qVlTFJKzu80Von/OUQADEkqyT2tpeVo7+mmEVUIIhvj/29gNRdDMEZquRq+lA7/eDYXXICkU27sbG0u61TO1aK4AhzL3tAqWVIUFn4etclhqnj4tlA80eW/yoIvKp/+xge8eqWO/M6lHU2yLxQAJD69ZrPILBq3PuhsZ5i/lSpsBTOLETT4qb1w7zIGe3Invs3IrnJRjkQkirBsTxvsqS4XTGzFdJyrSKtf62A3IG7LQIBHY+QXRp5Fm1ahogUcNOQFdCQWnMd7lKHk0tRFawPk5RP9M4kWESILiU0FGz9OfHdhTW2WJcNtC+Pc56R/bvASeO4wIDAQABAoIBAEKjtQXrqcDHxdMgBSfZ6GU2AQbWDGLLbKrS2XWNpwp1oiF1KHGd2ZaOrYP1miaYvnmboyK65C4QJzN0CdoX3LXclxlYSQZKTwX6yMClkJgbPTIXLHdRzfEHHbEybxQIur0YSjxvxkPlgTHZ/SXiFIUyPz8Bz+uS9rRiVQ+d+sAYnYXJM09u4V1bhLJ1931OEU8n41Wdy9tbMsaOxI1g12M2KOH7h4Ca5Jm00MJZX+CyKX1wydi1G6QpgLKbTQvh3dQm2Va5FX0xylQslo4qF45c5UxvPGvMTFBkbaoQfkLZHCPNSjc6yLa3llsB8/ZhUfBMP0jUhW0Ec0MkgQ974YECgYEA4w7t8Wxh/IzljtfG+ZkuSQBUi2LsQ5mLh3Oj+PnN14U6SEYGMUmTA6wtQhDJk9jiK2K9cGSEQLLB8BQgR3Y/ZB1MAPSgITIJ3Oxka1o4/hsUWuYJ8EnOSEMZ57vPw85bNAm4+ej1+o5hYzxOHtmQKEFDY2yd44A4+a8IhiyGB6MCgYEA2ExbyKuUMXhWQga+UAn8l8JWtDa5J3Tg0V8BwBaKlVeW8/efOLpvfA+P9lVUFDG48tLcOSW8CYDOFQXlV0kw/x2d34X1MwigqKB6ICTNvdSTOrMLOhWH1VUTBHbdahtHyV6EMCRcqg03nCMIqWIyYpR/diQEbku3E+eSkQtFz8ECgYEAvnOYXAeYDRk1t+IAEP5Ol4cCY0Qffvg80+nIoR8PbHZgk5zAtvjKqqrx71dbbXrfAps44Rw+3nHSQIjxJl/l/hig1rBZ3F43baqO9IjiAyo9oZ0Quw99SpmWEg0z0T62u2hoUp74LCjfQTilIjVFOK69UpkZumij4bLSSJDx/1cCgYEAuxfRjJJdbS0Z76LFm5YH131SYi+zmF2Q2YnEidL1rJhHCmB2aStao4USkZDdWVppECE0PHpXXCD+IVEoP4gfyYxksqO8pJgh37pv6L3s+PaXI38bhvJ4vB8KhCINA2r1fUk0LjBFtxIXuAbVxy4ZRwwL9LTS4FS914nHTY7ipAECgYEAqnEJNZ6opVJuKlO5HUEEp+oddCYBCLczcjw8hIEqYEErQ333hxEtaL/b+jeuB9nW3OaBVbIxZz+FGxBckVt3W4MxfpeBJvSstoBFjzrPjixb0/wtwt69AjnVyuJePHBQlMF11aXA6Pm/R9IBr/vC0atVChMGRS9g6FYzFmKTloA=-----END RSA PRIVATE KEY-----
          # key: ${{ secrets.KEY }}
          source: "src/dist"
          target: "src/dist"


      # - name: Copy env values for build
      #   run: cp ../.env ./dist/.env

      # - name: Restart process
      #   run: pm2 restart todo-ls-backend --update-env # the pm2 process must be defined