
name: todo-ls-backend
on:
  push:
    branches:
      - develop
jobs:
  test-build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install
      run: npm install

      - name: Run lint
      run: npm run lint

      - name: Run unit tests
      run: npm test

      - name: Build
      run: npm run build

      - name: Restart process
      run: pm2 restart todo-ls-backend # process with given name must be defined